export const KoreanPosition = {
  head: "머리",
  forehead: "이마",
  eyes: "눈",
  nose: "코",
  mouth: "입",
  cheek: "볼",
  chin: "턱",
  ears: "귀",
  back: "등",
  waist: "허리",
  hip: "엉덩이",
  neck: "목",
  chest: "가슴",
  stomach: "배",
  pelvis: "골반",
  sexOrgan: "생식기",
  shoulder: "어깨",
  upperArm: "윗팔",
  albow: "팔꿈치",
  forearm: "아랫팔",
  wrist: "손목",
  hand: "손",
  thigh: "허벅지",
  knee: "무릎",
  calf: "종아리",
  ankle: "발목",
  foot: "발",
  undefined
};
